pipeline {
    agent any

    environment {
        IMAGE_NAME = '2048-mobile-game'
        DOCKER_REGISTRY = "${env.GHCR_DOCKER_REGISTRY}"
        DOCKER_REGISTRY_CREDENTIALS = "${env.XIAOQI_GHCR_DOCKER_REGISTRY_CREDENTIALS}"
        KUBECONFIG = "${env.KUBECONFIG}"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    def appImage = docker.build("${XIAOQI_GHCR_DOCKER_REGISTRY_USERNAME}/${IMAGE_NAME}:${BUILD_NUMBER}")
                    appImage.tag 'latest'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry("https://${DOCKER_REGISTRY}", "${XIAOQI_GHCR_DOCKER_REGISTRY_CREDENTIALS}") {
                        docker.image("${XIAOQI_GHCR_DOCKER_REGISTRY_USERNAME}/${IMAGE_NAME}:${BUILD_NUMBER}").push()
                        docker.image("${XIAOQI_GHCR_DOCKER_REGISTRY_USERNAME}/${IMAGE_NAME}:latest").push()
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            agent {
                docker {
                    image 'alpine/k8s:1.34.1'
                    args '--entrypoint=""'
                }
            }
            steps {
                script {
                    withCredentials([file(credentialsId: "${KUBECONFIG_CREDENTIALS_FILE_ID}", variable: 'KUBECONFIG')]) {
                        sh """
                            # Check if namespace exists, create if not
                            kubectl get namespace demo || kubectl create namespace demo

                            # Always apply YAML files to sync all changes
                            envsubst < jenkins/k8s-deployment.yaml | kubectl apply -f -
                            envsubst < jenkins/k8s-service.yaml | kubectl apply -f -

                            # Rollout status
                            kubectl -n demo --kubeconfig=${KUBECONFIG} rollout status deployment/deployment-2048-game
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
        always {
            cleanWs()
        }
    }
}
