apiVersion: v1
kind: Service
metadata:
  name: game-2048
  namespace: demo
  labels:
    app: 2048-game
spec:
  type: LoadBalancer
  selector:
    app: 2048-game
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
